# Generated by Django 4.1.1 on 2024-02-01 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmpApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_author',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_pic',
        ),
    ]
