# Generated by Django 4.1.1 on 2024-02-01 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmpApp', '0002_remove_user_is_admin_remove_user_is_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='terms',
        ),
    ]
