# Generated by Django 4.1.1 on 2024-02-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmpApp', '0004_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=True),
        ),
    ]
