# Generated by Django 4.1.1 on 2024-02-12 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmpApp', '0010_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
