# Generated by Django 4.1.1 on 2024-02-12 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmpApp', '0012_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='profile_pics/'),
        ),
    ]
